# Generated by Django 3.1.3 on 2022-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='subject',
            new_name='question',
        ),
    ]
